language: rust
# https://github.com/rust-lang/rust/blob/master/RELEASES.md
rust:
  - 1.31.0
  - 1.31.1
  - 1.32.0
  - 1.33.0
  - 1.34.1
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: osx
      env:
        - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
        - DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include

