language: rust
rust:
  - 1.22.1
  - 1.23.0
  - 1.24.1
  - 1.25.0
  - 1.26.2
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: 1.22.1
    - rust: 1.23.0
    - rust: 1.24.1
    - rust: nightly
  include:
    - rust: stable
      os: osx
      env:
        - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
        - DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include

