language: rust
# https://github.com/rust-lang/rust/blob/master/RELEASES.md
rust:
  - 1.22.1
  - 1.23.0
  - 1.24.1
  - 1.25.0
  - 1.26.2
  - 1.27.0
  - 1.27.1
  - 1.27.2
  - 1.28.0
  - 1.29.0
  - 1.29.1
  - 1.29.2
  - 1.30.0
  - 1.30.1
  - 1.31.0
  - 1.31.1
  - 1.32.0
  - 1.33.0
  - 1.34.1
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: osx
      env:
        - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
        - DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include

