language: rust
rust:
  - 1.8.0
  - 1.12.1
  - 1.13.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: osx
      env:
        - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
        - DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include

